from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

RULE_PATH = ROOT / "toda_delta_image_rules.py"
BOOTSTRAP_PATH = ROOT / "toda_upstream_bootstrap.py"
TEST_PATH = ROOT / "tests" / "test_phase159_pi4_3_prop51_direct_delta_provenance.py"

RULE_TEXT = 'from homotopy_groups import (\n  FreeCyclicGroup,\n)\nfrom proof import (\n  InferenceRule,\n  PremisePattern,\n  Relation,\n  RelationType,\n)\nfrom toda_rules import (\n  TodaDeltaImageFreeCyclicStatement,\n  TodaDeltaImageUpToSignStatement,\n)\n\n\ndef free_cyclic_generator_delta_image_inference_rule():\n  def guard(\n    premises,\n    bindings,\n  ):\n    source_relation = (\n      premises[0].conclusion\n    )\n    delta_relation = (\n      premises[1].conclusion\n    )\n\n    if (\n      source_relation.relation_type\n      is not RelationType.EQUALITY\n    ):\n      return False\n\n    if not isinstance(\n      source_relation.rhs,\n      FreeCyclicGroup,\n    ):\n      return False\n\n    return (\n      source_relation.lhs\n      == delta_relation.map.source_group\n      and source_relation.rhs.generator\n      == delta_relation.element\n    )\n\n  def build_conclusion(\n    premises,\n  ):\n    delta_relation = (\n      premises[1].conclusion\n    )\n\n    return (\n      TodaDeltaImageFreeCyclicStatement(\n        map=delta_relation.map,\n        image_group=FreeCyclicGroup(\n          generator=(\n            delta_relation\n            .positive_value\n          ),\n        ),\n      )\n    )\n\n  return InferenceRule(\n    name=(\n      "free cyclic generator Delta "\n      "image"\n    ),\n    description=(\n      "If the source is freely generated by g "\n      "and Delta(g)=+/-x, then Im(Delta) "\n      "is freely generated by x."\n    ),\n    premise_patterns=(\n      PremisePattern(\n        statement_type=Relation,\n        relation_type=(\n          RelationType.EQUALITY\n        ),\n      ),\n      PremisePattern(\n        statement_type=(\n          TodaDeltaImageUpToSignStatement\n        ),\n      ),\n    ),\n    conclusion_builder=(\n      build_conclusion\n    ),\n    match_guard=guard,\n  )\n'
TEST_TEXT = 'from expression import (\n  GeneratorSymbol,\n  HomotopyElement,\n  Multiple,\n)\nfrom homotopy_groups import (\n  FreeCyclicGroup,\n  TodaDeltaMap,\n  TodaPrimaryGroup,\n)\nfrom proof import (\n  ProofRule,\n  ProofStep,\n  Relation,\n  RelationType,\n  find_inference_match,\n  run_inference_until_stable_with_history,\n)\nfrom toda_delta_image_rules import (\n  free_cyclic_generator_delta_image_inference_rule,\n)\nfrom toda_rules import (\n  TodaDeltaImageFreeCyclicStatement,\n  TodaDeltaImageUpToSignStatement,\n)\nfrom toda_upstream_bootstrap import (\n  _build_phase50_result,\n)\n\n\ndef _build_direct_delta_data():\n  pi_5_5 = TodaPrimaryGroup(\n    group_dimension=5,\n    sphere_dimension=5,\n  )\n  pi_3_2 = TodaPrimaryGroup(\n    group_dimension=3,\n    sphere_dimension=2,\n  )\n  iota_5 = HomotopyElement(\n    name="ι_5",\n    dimension=5,\n    generator=GeneratorSymbol(\n      family="ι",\n      index=5,\n    ),\n  )\n  eta_2 = HomotopyElement(\n    name="η₂",\n    dimension=2,\n    source=3,\n    target=2,\n    generator=GeneratorSymbol(\n      family="η",\n      index=2,\n    ),\n  )\n  two_eta_2 = Multiple(\n    coefficient=2,\n    expression=eta_2,\n  )\n  delta_map = TodaDeltaMap(\n    source_group=pi_5_5,\n    target_group=pi_3_2,\n  )\n  source_relation = Relation(\n    lhs=pi_5_5,\n    rhs=FreeCyclicGroup(\n      generator=iota_5,\n    ),\n    relation_type=(\n      RelationType.EQUALITY\n    ),\n  )\n  delta_relation = (\n    TodaDeltaImageUpToSignStatement(\n      map=delta_map,\n      element=iota_5,\n      positive_value=two_eta_2,\n    )\n  )\n  expected_image = (\n    TodaDeltaImageFreeCyclicStatement(\n      map=delta_map,\n      image_group=FreeCyclicGroup(\n        generator=two_eta_2,\n      ),\n    )\n  )\n\n  return {\n    "pi_5_5": pi_5_5,\n    "pi_3_2": pi_3_2,\n    "iota_5": iota_5,\n    "eta_2": eta_2,\n    "two_eta_2": two_eta_2,\n    "delta_map": delta_map,\n    "source_relation": source_relation,\n    "delta_relation": delta_relation,\n    "expected_image": expected_image,\n  }\n\n\ndef test_phase159_repair1_generic_direct_delta_image_rule_matches():\n  data = _build_direct_delta_data()\n\n  steps = (\n    ProofStep(\n      conclusion=data[\n        "source_relation"\n      ],\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=data[\n        "delta_relation"\n      ],\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n  )\n\n  assert find_inference_match(\n    free_cyclic_generator_delta_image_inference_rule(),\n    steps,\n  ) is not None\n\n\ndef test_phase159_repair1_generic_direct_delta_image_rule_derives_image():\n  data = _build_direct_delta_data()\n\n  source_step = ProofStep(\n    conclusion=data[\n      "source_relation"\n    ],\n    premises=(),\n    rule=ProofRule.GIVEN,\n  )\n  delta_step = ProofStep(\n    conclusion=data[\n      "delta_relation"\n    ],\n    premises=(),\n    rule=ProofRule.GIVEN,\n  )\n\n  result = (\n    run_inference_until_stable_with_history(\n      free_cyclic_generator_delta_image_inference_rule(),\n      (\n        source_step,\n        delta_step,\n      ),\n    )\n  )\n\n  derived = tuple(\n    step\n    for step in result.steps\n    if (\n      step.conclusion\n      == data[\n        "expected_image"\n      ]\n    )\n  )\n\n  assert len(derived) == 1\n  assert derived[0].premises == (\n    source_step,\n    delta_step,\n  )\n\n\ndef test_phase159_repair1_generic_direct_delta_image_rule_rejects_wrong_generator():\n  data = _build_direct_delta_data()\n\n  wrong_generator = HomotopyElement(\n    name="x",\n    dimension=5,\n    generator=GeneratorSymbol(\n      family="x",\n      index=5,\n    ),\n  )\n\n  wrong_source_relation = Relation(\n    lhs=data[\n      "pi_5_5"\n    ],\n    rhs=FreeCyclicGroup(\n      generator=wrong_generator,\n    ),\n    relation_type=(\n      RelationType.EQUALITY\n    ),\n  )\n\n  steps = (\n    ProofStep(\n      conclusion=wrong_source_relation,\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=data[\n        "delta_relation"\n      ],\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n  )\n\n  assert find_inference_match(\n    free_cyclic_generator_delta_image_inference_rule(),\n    steps,\n  ) is None\n\n\ndef test_phase159_repair1_phase50_image_uses_prop51_direct_delta_statement():\n  phase50 = _build_phase50_result()\n\n  image_steps = tuple(\n    step\n    for step in phase50[\n      "result"\n    ].steps\n    if isinstance(\n      step.conclusion,\n      TodaDeltaImageFreeCyclicStatement,\n    )\n  )\n\n  assert len(image_steps) == 1\n\n  image_step = image_steps[0]\n\n  direct_delta_premises = tuple(\n    premise\n    for premise in image_step.premises\n    if isinstance(\n      premise.conclusion,\n      TodaDeltaImageUpToSignStatement,\n    )\n  )\n\n  assert len(\n    direct_delta_premises\n  ) == 1\n\n  direct_delta_step = (\n    direct_delta_premises[0]\n  )\n\n  assert (\n    direct_delta_step\n    .inference_rule\n    is not None\n  )\n  assert (\n    direct_delta_step\n    .inference_rule\n    .literature_reference\n    is not None\n  )\n  assert (\n    direct_delta_step\n    .inference_rule\n    .literature_reference\n    .locator\n    == "Proposition 5.1"\n  )\n\n  positive_value = (\n    direct_delta_step\n    .conclusion\n    .positive_value\n  )\n\n  assert isinstance(\n    positive_value,\n    Multiple,\n  )\n  assert positive_value.coefficient == 2\n  assert (\n    positive_value\n    .expression\n    .generator\n    == GeneratorSymbol(\n      family="η",\n      index=2,\n    )\n  )\n\n\ndef test_phase159_repair1_final_step_ancestry_contains_prop51_direct_delta():\n  phase50 = _build_phase50_result()\n\n  pending = [\n    phase50[\n      "final_group_step"\n    ]\n  ]\n  seen = set()\n  ancestry = []\n\n  while pending:\n    step = pending.pop()\n    step_id = id(step)\n\n    if step_id in seen:\n      continue\n\n    seen.add(step_id)\n    ancestry.append(step)\n    pending.extend(\n      step.premises\n    )\n\n  direct_delta_steps = tuple(\n    step\n    for step in ancestry\n    if (\n      isinstance(\n        step.conclusion,\n        TodaDeltaImageUpToSignStatement,\n      )\n      and (\n        step.inference_rule\n        is not None\n      )\n      and (\n        step.inference_rule\n        .literature_reference\n        is not None\n      )\n      and (\n        step.inference_rule\n        .literature_reference\n        .locator\n        == "Proposition 5.1"\n      )\n    )\n  )\n\n  assert len(\n    direct_delta_steps\n  ) == 1\n'
NEW_FUNCTION = 'def _build_phase50_result():\n  pi_5_5 = TodaPrimaryGroup(\n    group_dimension=5,\n    sphere_dimension=5,\n  )\n  pi_3_2 = TodaPrimaryGroup(\n    group_dimension=3,\n    sphere_dimension=2,\n  )\n  pi_3_3 = TodaPrimaryGroup(\n    group_dimension=3,\n    sphere_dimension=3,\n  )\n  pi_4_3 = TodaPrimaryGroup(\n    group_dimension=4,\n    sphere_dimension=3,\n  )\n  pi_4_5 = TodaPrimaryGroup(\n    group_dimension=4,\n    sphere_dimension=5,\n  )\n\n  iota_2 = HomotopyElement(\n    name="ι_2",\n    dimension=2,\n    generator=GeneratorSymbol(\n      family="ι",\n      index=2,\n    ),\n  )\n  iota_3 = HomotopyElement(\n    name="ι_3",\n    dimension=3,\n    generator=GeneratorSymbol(\n      family="ι",\n      index=3,\n    ),\n  )\n  iota_5 = HomotopyElement(\n    name="ι_5",\n    dimension=5,\n    generator=GeneratorSymbol(\n      family="ι",\n      index=5,\n    ),\n  )\n  eta_2 = HomotopyElement(\n    name="η₂",\n    dimension=2,\n    source=3,\n    target=2,\n    generator=GeneratorSymbol(\n      family="η",\n      index=2,\n    ),\n  )\n  eta_3 = HomotopyElement(\n    name="η₃",\n    dimension=3,\n    source=4,\n    target=3,\n    generator=GeneratorSymbol(\n      family="η",\n      index=3,\n    ),\n  )\n\n  hopf_map = TodaHopfInvariantMap(\n    source_group=pi_3_2,\n    target_group=pi_3_3,\n  )\n\n  delta_map = TodaDeltaMap(\n    source_group=pi_5_5,\n    target_group=pi_3_2,\n  )\n\n  prop51_delta_step = ProofStep(\n    conclusion=(\n      TodaDeltaImageUpToSignStatement(\n        map=delta_map,\n        element=iota_5,\n        positive_value=Multiple(\n          coefficient=2,\n          expression=eta_2,\n        ),\n      )\n    ),\n    premises=(),\n    rule=ProofRule.INFERENCE,\n    inference_rule=InferenceRule(\n      name=(\n        "Toda Proposition 5.1 "\n        "Delta iota_5"\n      ),\n      description=(\n        "Toda Proposition 5.1 gives "\n        "Delta(iota_5)=+/-2 eta_2."\n      ),\n      literature_reference=(\n        LiteratureReference(\n          label="Toda Proposition 5.1",\n          author="H. Toda",\n          title=(\n            "Composition Methods in "\n            "Homotopy Groups of Spheres"\n          ),\n          year=1962,\n          locator="Proposition 5.1",\n        )\n      ),\n    ),\n  )\n\n  premise_steps = (\n    ProofStep(\n      conclusion=WhiteheadProduct(\n        left=iota_2,\n        right=iota_2,\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=TodaPi32Eta2DefinitionStatement(\n        map=hopf_map,\n        element=eta_2,\n        image=iota_3,\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=Relation(\n        lhs=MapApplication(\n          map=EHP_H_MAP,\n          expression=eta_2,\n        ),\n        rhs=iota_3,\n        relation_type=RelationType.EQUALITY,\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=TodaHopfInvariantInjectiveStatement(\n        map=hopf_map,\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=pi_5_5_free_cyclic_fact(),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=pi_4_5_zero_fact(),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=delta_map,\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    prop51_delta_step,\n    ProofStep(\n      conclusion=TodaProp42ExactnessStatement(\n        window=TodaEHPExactnessWindow(\n          source_term=pi_5_5,\n          middle_term=pi_3_2,\n          target_term=pi_4_3,\n          first_map=EHP_DELTA_MAP,\n          second_map=EHP_E_MAP,\n        ),\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=TodaProp42ExactnessStatement(\n        window=TodaEHPExactnessWindow(\n          source_term=pi_3_2,\n          middle_term=pi_4_3,\n          target_term=pi_4_5,\n          first_map=EHP_E_MAP,\n          second_map=EHP_H_MAP,\n        ),\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=Relation(\n        lhs=pi_3_2,\n        rhs=FreeCyclicGroup(\n          generator=eta_2,\n        ),\n        relation_type=RelationType.EQUALITY,\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n    ProofStep(\n      conclusion=toda_eta_family_definition_statement(\n        3\n      ),\n      premises=(),\n      rule=ProofRule.GIVEN,\n    ),\n  )\n\n  rules = (\n    toda_prop27_iota2_whitehead_hopf_invariant_inference_rule(),\n    toda_pi3_2_whitehead_square_up_to_sign_inference_rule(),\n    toda_delta_iota5_whitehead_square_inference_rule(),\n    free_cyclic_generator_delta_image_inference_rule(),\n    toda_pi4_3_delta_image_free_cyclic_inference_rule(),\n    toda_pi4_3_exactness_delta_image_to_suspension_kernel_inference_rule(),\n    toda_pi4_3_zero_right_implies_suspension_surjective_inference_rule(),\n    toda_pi4_3_finite_cyclic_inference_rule(),\n    toda_eta3_suspension_relation_inference_rule(),\n    toda_pi4_3_eta3_generator_inference_rule(),\n  )\n\n  result = run_inference_until_stable_with_history(\n    rules,\n    premise_steps,\n  )\n\n  final_group_step = _find_unique_step(\n    result.steps,\n    lambda step: (\n      isinstance(\n        step.conclusion,\n        Relation,\n      )\n      and step.conclusion.lhs\n      == pi_4_3\n      and isinstance(\n        step.conclusion.rhs,\n        FiniteCyclicGroup,\n      )\n      and step.conclusion.rhs.order\n      == 2\n      and step.conclusion.rhs.generator\n      == eta_3\n    ),\n    "pi_4^3",\n  )\n\n  return {\n    "result": result,\n    "final_group_step": final_group_step,\n  }\n'

OLD_IMPORT_ANCHOR = '''from relation_rules import (
  equality_preserved_under_left_composition_inference_rule,
  equality_preserved_under_right_composition_inference_rule,
  equality_transitivity_inference_rule,
)
'''

NEW_IMPORT_ANCHOR = '''from relation_rules import (
  equality_preserved_under_left_composition_inference_rule,
  equality_preserved_under_right_composition_inference_rule,
  equality_transitivity_inference_rule,
)
from toda_delta_image_rules import (
  free_cyclic_generator_delta_image_inference_rule,
)
'''

OLD_TODA_IMPORT = '''  TodaBracketMembershipStatement,
  TodaDeltaZeroStatement,
  TodaHopfInvariantInjectiveStatement,
'''

NEW_TODA_IMPORT = '''  TodaBracketMembershipStatement,
  TodaDeltaImageUpToSignStatement,
  TodaDeltaZeroStatement,
  TodaHopfInvariantInjectiveStatement,
'''

FUNCTION_START = "def _build_phase50_result():"
NEXT_FUNCTION = "\ndef build_toda_52_composition_isomorphism_step("


def replace_once(text, old, new, label):
  count = text.count(old)
  if count != 1:
    raise RuntimeError(
      f"{label}: expected one match, found {count}"
    )
  return text.replace(old, new, 1)


def main():
  if RULE_PATH.exists():
    raise RuntimeError(
      "toda_delta_image_rules.py already exists"
    )

  if TEST_PATH.exists():
    raise RuntimeError(
      "Phase 159 repair1 test already exists"
    )

  bootstrap = BOOTSTRAP_PATH.read_text(
    encoding="utf-8"
  )

  bootstrap = replace_once(
    bootstrap,
    OLD_IMPORT_ANCHOR,
    NEW_IMPORT_ANCHOR,
    "relation import anchor",
  )

  bootstrap = replace_once(
    bootstrap,
    OLD_TODA_IMPORT,
    NEW_TODA_IMPORT,
    "toda_rules import anchor",
  )

  start = bootstrap.find(
    FUNCTION_START
  )
  if start < 0:
    raise RuntimeError(
      "_build_phase50_result not found"
    )

  end = bootstrap.find(
    NEXT_FUNCTION,
    start,
  )
  if end < 0:
    raise RuntimeError(
      "next function boundary not found"
    )

  bootstrap = (
    bootstrap[:start]
    + NEW_FUNCTION
    + bootstrap[end:]
  )

  RULE_PATH.write_text(
    RULE_TEXT,
    encoding="utf-8",
    newline="\n",
  )
  BOOTSTRAP_PATH.write_text(
    bootstrap,
    encoding="utf-8",
    newline="\n",
  )
  TEST_PATH.write_text(
    TEST_TEXT,
    encoding="utf-8",
    newline="\n",
  )

  print("Phase 159 pi_4^3 repair1 applied.")
  print("Added: toda_delta_image_rules.py")
  print("Changed: toda_upstream_bootstrap.py")
  print(
    "Added: tests/"
    "test_phase159_pi4_3_prop51_direct_delta_provenance.py"
  )
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
