from homotopy_groups import (
  FreeCyclicGroup,
)
from proof import (
  InferenceRule,
  PremisePattern,
  Relation,
  RelationType,
)
from toda_rules import (
  TodaDeltaImageFreeCyclicStatement,
  TodaDeltaImageUpToSignStatement,
)


def free_cyclic_generator_delta_image_inference_rule():
  def guard(
    premises,
    bindings,
  ):
    source_relation = (
      premises[0].conclusion
    )
    delta_relation = (
      premises[1].conclusion
    )

    if (
      source_relation.relation_type
      is not RelationType.EQUALITY
    ):
      return False

    if not isinstance(
      source_relation.rhs,
      FreeCyclicGroup,
    ):
      return False

    return (
      source_relation.lhs
      == delta_relation.map.source_group
      and source_relation.rhs.generator
      == delta_relation.element
    )

  def build_conclusion(
    premises,
  ):
    delta_relation = (
      premises[1].conclusion
    )

    return (
      TodaDeltaImageFreeCyclicStatement(
        map=delta_relation.map,
        image_group=FreeCyclicGroup(
          generator=(
            delta_relation
            .positive_value
          ),
        ),
      )
    )

  return InferenceRule(
    name=(
      "free cyclic generator Delta "
      "image"
    ),
    description=(
      "If the source is freely generated by g "
      "and Delta(g)=+/-x, then Im(Delta) "
      "is freely generated by x."
    ),
    premise_patterns=(
      PremisePattern(
        statement_type=Relation,
        relation_type=(
          RelationType.EQUALITY
        ),
      ),
      PremisePattern(
        statement_type=(
          TodaDeltaImageUpToSignStatement
        ),
      ),
    ),
    conclusion_builder=(
      build_conclusion
    ),
    match_guard=guard,
  )
