from dataclasses import dataclass

from proof import (
  InferenceRule,
  LiteratureReference,
  ProofRule,
  ProofStep,
)
from toda_group_proof_narrative_references import (
  TodaGroupProofNarrativeReferenceEntry,
  filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary,
)


@dataclass(frozen=True)
class _TargetGroup:
  group_dimension: int
  sphere_dimension: int


@dataclass(frozen=True)
class _RelationLike:
  lhs: _TargetGroup
  rhs: str


def _reference(
  locator: str,
) -> LiteratureReference:
  return LiteratureReference(
    label="Toda " + locator,
    locator=locator,
  )


def _step(
  rule_name: str,
  locator: str,
  conclusion,
) -> ProofStep:
  return ProofStep(
    conclusion=conclusion,
    premises=(),
    rule=ProofRule.INFERENCE,
    inference_rule=InferenceRule(
      name=rule_name,
      literature_reference=_reference(
        locator
      ),
    ),
  )


def test_phase157_r4_r3_filter_keeps_only_earlier_fixed_same_theorem_group_result():
  root_step = _step(
    "Toda Proposition 5.15 pi_15^8 final decomposition",
    "Proposition 5.15",
    _RelationLike(
      lhs=_TargetGroup(
        group_dimension=15,
        sphere_dimension=8,
      ),
      rhs="target",
    ),
  )
  earlier_step = _step(
    "Toda Proposition 5.15 pi_14^7 finite cyclic",
    "Proposition 5.15",
    "earlier fixed group result",
  )
  target_step = _step(
    "Toda Proposition 5.15 pi_15^8 final decomposition",
    "Proposition 5.15",
    "target fixed group result",
  )
  internal_step = _step(
    "Toda Proposition 5.15 sigma_8 transported decomposition",
    "Proposition 5.15",
    "proof-internal decomposition",
  )

  entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=_reference(
      "Proposition 5.15"
    ),
    proof_steps=(
      earlier_step,
      target_step,
      internal_step,
    ),
  )

  filtered = (
    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(
      (
        entry,
      ),
      root_step,
    )
  )

  assert len(
    filtered
  ) == 1
  assert filtered[
    0
  ].proof_steps == (
    earlier_step,
  )


def test_phase157_r4_r3_filter_removes_proof_internal_prop511_step():
  root_step = _step(
    "Toda Proposition 5.15 pi_12^5 finite cyclic",
    "Proposition 5.15",
    _RelationLike(
      lhs=_TargetGroup(
        group_dimension=12,
        sphere_dimension=5,
      ),
      rhs="target",
    ),
  )
  fixed_step = _step(
    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",
    "Proposition 5.11",
    "fixed group result",
  )
  internal_step = _step(
    "Toda Proposition 5.11 pi_12^6 suspension isomorphism",
    "Proposition 5.11",
    "proof-internal map property",
  )

  entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=_reference(
      "Proposition 5.11"
    ),
    proof_steps=(
      fixed_step,
      internal_step,
    ),
  )

  filtered = (
    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(
      (
        entry,
      ),
      root_step,
    )
  )

  assert len(
    filtered
  ) == 1
  assert filtered[
    0
  ].proof_steps == (
    fixed_step,
  )


def test_phase157_r4_r3_filter_is_noop_outside_representative_targets():
  root_step = _step(
    "Toda Proposition 5.15 pi_13^6 finite cyclic",
    "Proposition 5.15",
    _RelationLike(
      lhs=_TargetGroup(
        group_dimension=13,
        sphere_dimension=6,
      ),
      rhs="target",
    ),
  )
  step = _step(
    "Toda Proposition 5.15 pi_12^5 finite cyclic",
    "Proposition 5.15",
    "fixed group result",
  )
  entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=_reference(
      "Proposition 5.15"
    ),
    proof_steps=(
      step,
    ),
  )

  filtered = (
    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(
      (
        entry,
      ),
      root_step,
    )
  )

  assert filtered == (
    entry,
  )
