from dataclasses import dataclass

from proof import (
  InferenceRule,
  LiteratureReference,
  ProofRule,
  ProofStep,
)
from toda_group_proof_narrative_references import (
  TodaGroupProofNarrativeReferenceEntry,
  restore_phase157_r4_representative_fixed_reference_entries_after_body_usage,
)


@dataclass(frozen=True)
class _TargetGroup:
  group_dimension: int
  sphere_dimension: int


@dataclass(frozen=True)
class _RelationLike:
  lhs: _TargetGroup
  rhs: str


def _reference(
  locator: str,
) -> LiteratureReference:
  return LiteratureReference(
    label="Toda " + locator,
    locator=locator,
  )


def _step(
  rule_name: str,
  locator: str,
  conclusion,
  premises=(),
) -> ProofStep:
  return ProofStep(
    conclusion=conclusion,
    premises=premises,
    rule=ProofRule.INFERENCE,
    inference_rule=InferenceRule(
      name=rule_name,
      literature_reference=_reference(
        locator
      ),
    ),
  )


def test_phase157_r4_r3_restore_uses_step_identity_without_hashing_recursive_proof_graph():
  deep_leaf = _step(
    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",
    "Proposition 5.11",
    "leaf",
  )
  deep_middle = _step(
    "Toda Proposition 5.11 pi_11^5 nu_5 squared",
    "Proposition 5.11",
    "middle",
    premises=(
      deep_leaf,
    ),
  )
  fixed_step = _step(
    "Toda Lemma 5.13 sigma triple-prime definition",
    "Lemma 5.13",
    "sigma triple-prime fixed statement",
    premises=(
      deep_middle,
    ),
  )
  retained_step = _step(
    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",
    "Proposition 5.11",
    "retained fixed result",
  )
  root_step = _step(
    "Toda Proposition 5.15 pi_12^5 finite cyclic",
    "Proposition 5.15",
    _RelationLike(
      lhs=_TargetGroup(
        group_dimension=12,
        sphere_dimension=5,
      ),
      rhs="target",
    ),
    premises=(
      fixed_step,
      retained_step,
    ),
  )

  lemma_entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=_reference(
      "Lemma 5.13"
    ),
    proof_steps=(
      fixed_step,
    ),
  )
  prop511_entry = TodaGroupProofNarrativeReferenceEntry(
    number=2,
    reference=_reference(
      "Proposition 5.11"
    ),
    proof_steps=(
      retained_step,
    ),
  )
  filtered_prop511_entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=prop511_entry.reference,
    proof_steps=prop511_entry.proof_steps,
  )

  (
    restored_entries,
    restored_lines,
    restored_body,
  ) = (
    restore_phase157_r4_representative_fixed_reference_entries_after_body_usage(
      (
        lemma_entry,
        prop511_entry,
      ),
      {
        1: (
          "sigma-triple-prime fixed",
        ),
        2: (
          "pi10_4 fixed",
        ),
      },
      (
        filtered_prop511_entry,
      ),
      {
        1: (
          "pi10_4 fixed",
        ),
      },
      "uses [R1]",
      root_step,
      frozenset(
        {
          id(
            fixed_step
          ),
          id(
            retained_step
          ),
        }
      ),
    )
  )

  assert tuple(
    entry.reference.locator
    for entry in restored_entries
  ) == (
    "Lemma 5.13",
    "Proposition 5.11",
  )
  assert restored_lines == {
    1: (
      "sigma-triple-prime fixed",
    ),
    2: (
      "pi10_4 fixed",
    ),
  }
  assert restored_body == "uses [R2]"


def test_phase157_r4_r3_restore_does_not_add_unused_fixed_reference():
  unused_step = _step(
    "Toda Lemma 5.13 sigma triple-prime definition",
    "Lemma 5.13",
    "unused fixed statement",
  )
  retained_step = _step(
    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",
    "Proposition 5.11",
    "retained fixed result",
  )
  root_step = _step(
    "Toda Proposition 5.15 pi_12^5 finite cyclic",
    "Proposition 5.15",
    _RelationLike(
      lhs=_TargetGroup(
        group_dimension=12,
        sphere_dimension=5,
      ),
      rhs="target",
    ),
  )

  unused_entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=_reference(
      "Lemma 5.13"
    ),
    proof_steps=(
      unused_step,
    ),
  )
  retained_entry = TodaGroupProofNarrativeReferenceEntry(
    number=2,
    reference=_reference(
      "Proposition 5.11"
    ),
    proof_steps=(
      retained_step,
    ),
  )
  filtered_retained_entry = TodaGroupProofNarrativeReferenceEntry(
    number=1,
    reference=retained_entry.reference,
    proof_steps=retained_entry.proof_steps,
  )

  (
    restored_entries,
    restored_lines,
    restored_body,
  ) = (
    restore_phase157_r4_representative_fixed_reference_entries_after_body_usage(
      (
        unused_entry,
        retained_entry,
      ),
      {
        1: (
          "unused",
        ),
        2: (
          "retained",
        ),
      },
      (
        filtered_retained_entry,
      ),
      {
        1: (
          "retained",
        ),
      },
      "uses [R1]",
      root_step,
      frozenset(
        {
          id(
            retained_step
          ),
        }
      ),
    )
  )

  assert len(
    restored_entries
  ) == 1
  assert (
    restored_entries[
      0
    ].reference.locator
    == "Proposition 5.11"
  )
  assert restored_lines == {
    1: (
      "retained",
    ),
  }
  assert restored_body == "uses [R1]"
