from collections import defaultdict

from rule_catalog import (
  RuleRelevanceCategory,
)
from standard_production_applicability_catalog import (
  build_standard_production_applicability_catalog,
)


SECOND_WAVE_EXPECTED = {
  RuleRelevanceCategory.THEOREM_SPECIFIC: (
    "Toda 4.5 stable-range iterated suspension isomorphism",
    "Toda Delta iota_5 Whitehead-square relation",
    (
      "Toda Proposition 2.7 iota_2 Whitehead-square "
      "Hopf invariant up to sign"
    ),
    (
      "Toda pi_3^2 Whitehead square equals twice "
      "eta_2 up to sign"
    ),
    "Toda pi_4^3 Delta image generated by twice eta_2",
    "Toda pi_4^3 finite cyclic quotient calculation",
    "Toda 5.4 nu-prime higher triple eta transport",
    "Toda Lemma 5.4 pi_6^5 finite-cyclic specialization",
    "Toda Proposition 5.3 n=3 Hopf eta_5 surjectivity",
    "Toda 5.4 n=5 t=3 specialization",
    (
      "Toda (5.6) nu_4 Proposition 4.4 "
      "specialization premises"
    ),
    "Toda (5.6) nu_4 decomposition integration",
    (
      "Toda (5.6) nu_4 decomposition "
      "isomorphism semantics"
    ),
    "Toda 4.8 Lemma 5.4 Hopf odd multiple",
    "Toda 5.2 eta_2 composition isomorphism",
    (
      "Toda 5.3 nu-prime Lemma 5.2 "
      "Hopf specialization"
    ),
    (
      "Toda 5.3 nu-prime Lemma 5.2 "
      "double specialization"
    ),
    "Toda 5.5 nu-family finite-dimensional integration",
  ),
  RuleRelevanceCategory.STRUCTURAL: (
    "Toda EHP exactness zero-left Hopf injectivity",
    "Toda EHP exactness injective-right Delta zero",
    "Toda EHP exactness zero-Delta Hopf surjectivity",
    (
      "Toda pi_4^3 E-H exactness zero-right "
      "suspension surjectivity"
    ),
    (
      "Toda pi_4^3 exactness Delta image equals "
      "E kernel"
    ),
  ),
  RuleRelevanceCategory.MAP_PROPERTY: (
    (
      "Toda Hopf invariant injective and "
      "surjective implies isomorphism"
    ),
    "Toda suspension isomorphism implies injectivity",
  ),
  RuleRelevanceCategory.BRIDGE: (
    "Toda eta_3 notation suspension bridge",
    "Toda pi_4^3 eta_3 generator notation",
    "Toda 5.3 eta_4 suspension bridge",
    "Toda 5.3 eta_5 iterated suspension bridge",
  ),
}


DEFERRED_FAMILIES = (
  "Toda pi_3^2 define eta_2 as unique Hopf preimage",
  "Toda pi_3^2 eta_2 Hopf relation",
  (
    "Toda 5.4 indeterminacy double nu-prime "
    "generator bridge"
  ),
  "Toda 5.4 nu-prime suspended bracket inclusion",
  (
    "Toda 5.4 t>=1 indeterminacy generated by "
    "eta triple composition"
  ),
  "Toda 5.4 t>=1 up-to-sign integration",
  "Toda 4.5 pi_4^3 finite-cyclic transport",
  "Toda 5.2 pi_4^2 finite-cyclic transport",
  "Toda 5.5 nu-family double suspension transport",
  (
    "Toda Delta iota_5 twice eta_2 "
    "up-to-sign bridge"
  ),
)


def _families(
  catalog,
):
  families = defaultdict(
    list
  )

  for entry in catalog.entries():
    families[
      entry.rule.name
    ].append(
      entry
    )

  return {
    name: tuple(
      entries
    )
    for name, entries
    in families.items()
  }


def test_phase103_6d10_second_wave_assigns_all_29_family_categories():
  catalog = (
    build_standard_production_applicability_catalog()
  )

  families = _families(
    catalog
  )

  checked = 0

  for (
    expected_category,
    names,
  ) in SECOND_WAVE_EXPECTED.items():
    for name in names:
      entries = families[
        name
      ]

      assert all(
        entry.relevance_category
        is expected_category
        for entry in entries
      )

      checked += 1

  assert checked == 29


def test_phase103_6d10_second_wave_affects_exactly_408_catalog_entries():
  catalog = (
    build_standard_production_applicability_catalog()
  )

  families = _families(
    catalog
  )

  second_wave_names = {
    name
    for names
    in SECOND_WAVE_EXPECTED.values()
    for name in names
  }

  affected_entries = tuple(
    entry
    for name in second_wave_names
    for entry in families[
      name
    ]
  )

  assert len(
    affected_entries
  ) == 408

  assert all(
    entry.relevance_category
    is not RuleRelevanceCategory.UNCLASSIFIED
    for entry in affected_entries
  )


def test_phase103_6d10_second_wave_families_remain_consistently_classified():
  catalog = (
    build_standard_production_applicability_catalog()
  )

  families = _families(
    catalog
  )

  checked = 0

  for (
    expected_category,
    names,
  ) in SECOND_WAVE_EXPECTED.items():
    for name in names:
      entries = families[
        name
      ]

      categories = {
        entry.relevance_category
        for entry in entries
      }

      assert categories == {
        expected_category
      }

      checked += 1

  assert checked == 29

  assert len(
    families
  ) == 267


def test_phase103_6d10_catalog_size_and_fixed_point_safety_are_unchanged():
  catalog = (
    build_standard_production_applicability_catalog()
  )

  entries = (
    catalog.entries()
  )

  assert len(
    entries
  ) == 1188

  assert all(
    entry.fixed_point_safe
    is False
    for entry in entries
  )



def test_phase103_6d10_factory_provenance_uses_function_qualname():
  from standard_production_applicability_catalog import (
    _inference_rule_factory_name,
  )

  catalog = (
    build_standard_production_applicability_catalog()
  )

  families = _families(
    catalog
  )

  representative = families[
    "Toda EHP exactness zero-left Hopf injectivity"
  ][
    0
  ].rule

  builder = (
    representative.conclusion_builder
  )

  assert callable(
    builder
  )

  assert ".<locals>." in (
    builder.__qualname__
  )

  assert (
    _inference_rule_factory_name(
      representative
    )
    == (
      "toda_exactness_zero_left_implies_"
      "hopf_injective_inference_rule"
    )
  )
