$ErrorActionPreference = "Stop"

python ".\phase143_docs_completion\apply_phase143_docs_completion.py"
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

Write-Host ""
Write-Host "=============================================================="
Write-Host "Phase 143 documentation update complete."
Write-Host "=============================================================="
Write-Host ""
Write-Host "Changed:"
Write-Host "  README.md"
Write-Host "  docs\design.md"
Write-Host "  docs\development_log.md"
Write-Host "  docs\roadmap.md"
Write-Host "  docs\proof_records.md"
Write-Host ""
Write-Host "Full updated copies:"
Write-Host "  phase143_docs_completion\updated_full_documents\README.md"
Write-Host "  phase143_docs_completion\updated_full_documents\docs\design.md"
Write-Host "  phase143_docs_completion\updated_full_documents\docs\development_log.md"
Write-Host "  phase143_docs_completion\updated_full_documents\docs\roadmap.md"
Write-Host "  phase143_docs_completion\updated_full_documents\docs\proof_records.md"
Write-Host ""
Write-Host "No pytest run is required: documentation-only update after the"
Write-Host "already completed Phase 143 final regression (9980 passed)."
