from pathlib import Path
import sys

from proof import (
  ProofRule,
)
from probes.probe_phase50_capabilities import (
  print_separator,
)


# Phase 69-3 の focused builder を
# representative fixture としてそのまま再利用する。
# theorem logic は probe 側へ複製しない。
_TESTS_DIR = (
  Path(__file__)
  .resolve()
  .parents[1]
  / "tests"
)

if str(_TESTS_DIR) not in sys.path:
  sys.path.insert(
    0,
    str(_TESTS_DIR),
  )

from test_phase69_delta_iota11 import (  # noqa: E402
  build_phase69_3_data,
)


def build_phase69_representative_result():
  return build_phase69_3_data()


def print_section(
  title,
):
  print()
  print_separator()
  print(
    title
  )
  print_separator()
  print()


def print_phase69_result(
  representative,
):
  print_section(
    "Toda Equation (5.10) result"
  )

  print(
    "Δ(ι₁₁) = ν₅η₈"
  )
  print()

  print(
    "result derived = "
    f"{representative['final_step'].rule == ProofRule.INFERENCE}"
  )


def print_phase69_derivation_chain(
  representative,
):
  print_section(
    "Proof-style derivation"
  )

  print(
    "Phase 68:"
  )
  print(
    "π_10^6 = 0"
  )
  print()

  print(
    "Toda Proposition 4.2:"
  )
  print(
    "π_11^11 "
    "─Δ→ π_9^5 "
    "─E→ π_10^6"
  )
  print(
    "is exact"
  )
  print()

  print(
    "π_10^6 = 0"
  )
  print("↓")
  print(
    "E: π_9^5 → π_10^6 "
    "is zero"
  )
  print("↓")
  print(
    "ker(E) = π_9^5"
  )
  print("↓ exactness")
  print(
    "Im(Δ) = π_9^5"
  )
  print("↓")
  print(
    "Δ: π_11^11 → π_9^5 "
    "is surjective"
  )
  print()

  print(
    "π_11^11 = Z{ι₁₁}"
  )
  print()

  print(
    "Phase 68:"
  )
  print(
    "π_9^5 = Z/2{ν₅η₈}"
  )
  print()

  print(
    "Δ is surjective"
  )
  print(
    "and π_11^11 is generated by ι₁₁"
  )
  print("↓")
  print(
    "Δ(ι₁₁) is the nonzero generator "
    "of π_9^5"
  )
  print()

  print(
    "Since π_9^5 has order two,"
  )
  print(
    "the possible sign is immaterial."
  )
  print("↓")
  print(
    "Δ(ι₁₁) = ν₅η₈"
  )


def print_phase69_exact_sequence():
  print_section(
    "EHP exact sequence used"
  )

  print(
    "π_11^11 "
    "─Δ→ "
    "π_9^5 "
    "─E→ "
    "π_10^6"
  )
  print()

  print(
    "π_10^6 = 0"
  )
  print(
    "therefore Δ is surjective."
  )


def print_phase69_provenance(
  representative,
):
  print_section(
    "Provenance / integration"
  )

  final_step = (
    representative[
      "final_step"
    ]
  )

  delta_surjective_step = (
    representative[
      "delta_surjective_step"
    ]
  )

  pi11_11_step = (
    representative[
      "pi11_11_step"
    ]
  )

  pi9_5_step = (
    representative[
      "pi9_5_step"
    ]
  )

  phase69_2 = (
    representative[
      "phase69_2"
    ]
  )

  pi10_6_zero_step = (
    phase69_2[
      "pi10_6_zero_step"
    ]
  )

  exactness_step = (
    phase69_2[
      "exactness_step"
    ]
  )

  exactness_window_step = (
    phase69_2[
      "exactness_window_step"
    ]
  )

  print(
    "π_10^6=0 derived = "
    f"{pi10_6_zero_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "structural exactness window "
    "remains GIVEN = "
    f"{exactness_window_step.rule == ProofRule.GIVEN}"
  )

  print(
    "Toda Proposition 4.2 "
    "exactness derived = "
    f"{exactness_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "Delta surjective derived = "
    f"{delta_surjective_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "π_11^11 source group "
    "remains foundational GIVEN = "
    f"{pi11_11_step.rule == ProofRule.GIVEN}"
  )

  print(
    "π_9^5 result derived = "
    f"{pi9_5_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "Toda (5.10) derived = "
    f"{final_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "Toda (5.10) is GIVEN = "
    f"{final_step.rule == ProofRule.GIVEN}"
  )

  print(
    "final premise count = "
    f"{len(final_step.premises)}"
  )

  print(
    "fixed point = "
    f"{representative['result'].termination_reason.value == 'fixed_point'}"
  )


def print_phase69_literature():
  print_section(
    "Literature / source"
  )

  print(
    "[Toda Equation (5.10)]"
  )
  print(
    "Locator: Equation (5.10)"
  )
  print(
    "Author: H. Toda"
  )
  print(
    "Source: Composition Methods in "
    "Homotopy Groups of Spheres"
  )
  print(
    "Year: 1962"
  )
  print(
    "Statement:"
  )
  print(
    "  Δ(ι₁₁) = ν₅η₈"
  )
  print()

  print(
    "The literature information in this "
    "probe is presentation metadata."
  )
  print(
    "No new theorem-search or literature "
    "inference mechanism is added."
  )


def print_phase69_related_result():
  print_section(
    "Related previously derived result"
  )

  print(
    "Toda Equation (5.11):"
  )
  print(
    "Δ(η₉) = Eν′η₇"
  )
  print()

  print(
    "This relation was already derived "
    "in Phase 68."
  )
  print(
    "Phase 69 does not reimplement "
    "Equation (5.11)."
  )


def print_phase69_boundary():
  print_section(
    "Phase 69 representative probe boundary"
  )

  print(
    "Displayed:"
  )
  print(
    "  Δ(ι₁₁) = ν₅η₈"
  )
  print(
    "  EHP exact sequence used"
  )
  print(
    "  Δ surjectivity prerequisite"
  )
  print(
    "  representative proof-style display"
  )
  print(
    "  machine provenance status"
  )
  print(
    "  Toda Equation (5.10) source metadata"
  )
  print(
    "  previously derived Toda (5.11)"
  )
  print()

  print(
    "Not added in Phase 69-5:"
  )
  print(
    "  new mathematical inference rules"
  )
  print(
    "  new theorem aggregate"
  )
  print(
    "  new literature statement class"
  )
  print(
    "  stable (G_4;2)=0"
  )
  print(
    "  automatic proof narrative generation"
  )
  print(
    "  persistent Proof Repository"
  )
  print()

  print(
    "The proof-style derivation above is "
    "hand-authored presentation code."
  )
  print(
    "It is not yet generated "
    "automatically from the ProofStep graph."
  )


def main():
  print(
    "EHP Proof Tracer"
  )
  print(
    "Phase 69 capability demonstration"
  )

  representative = (
    build_phase69_representative_result()
  )

  print_phase69_result(
    representative
  )

  print_phase69_derivation_chain(
    representative
  )

  print_phase69_exact_sequence()

  print_phase69_provenance(
    representative
  )

  print_phase69_literature()

  print_phase69_related_result()

  print_phase69_boundary()


if __name__ == "__main__":
  main()


