from pathlib import Path
import sys

from proof import (
  ProofRule,
)
from probes.probe_phase50_capabilities import (
  print_separator,
)


# Phase 76-5 の integration / provenance builder を
# representative fixture としてそのまま再利用する。
#
# theorem logic や kernel / exactness calculation を
# probe 側へ複製しない。
_TESTS_DIR = (
  Path(__file__)
  .resolve()
  .parents[1]
  / "tests"
)

if str(_TESTS_DIR) not in sys.path:
  sys.path.insert(
    0,
    str(_TESTS_DIR),
  )

from test_phase76_applicability_provenance import (  # noqa: E402
  build_phase76_5_data,
)


def build_phase76_representative_result():
  return build_phase76_5_data()


def collect_ancestor_steps(
  step,
):
  stack = list(
    step.premises
  )

  seen_ids = set()
  ancestors = []

  while stack:
    current = stack.pop()
    current_id = id(
      current
    )

    if current_id in seen_ids:
      continue

    seen_ids.add(
      current_id
    )
    ancestors.append(
      current
    )
    stack.extend(
      current.premises
    )

  return tuple(
    ancestors
  )


def print_section(
  title,
):
  print()
  print_separator()
  print(
    title
  )
  print_separator()
  print()


def print_phase76_result(
  representative,
):
  final_step = (
    representative[
      "final_step"
    ]
  )

  print_section(
    "Toda Equation (5.16) result"
  )

  print(
    "Ker("
    "E: π_15^8 -> π_16^9"
    ")"
  )
  print(
    "= Z{2σ₈-Eσ'}"
  )
  print()

  print(
    "Im("
    "Δ: π_17^17 -> π_15^8"
    ")"
  )
  print(
    "= Z{2σ₈-Eσ'}"
  )
  print()

  print(
    "π_17^17 = Z{ι₁₇}"
  )
  print()

  print(
    "Δ(ι₁₇)"
  )
  print(
    "= ±(2σ₈-Eσ')"
  )
  print()

  print(
    "statement type = "
    f"{type(final_step.conclusion).__name__}"
  )

  print(
    "derived = "
    f"{final_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "is GIVEN = "
    f"{final_step.rule == ProofRule.GIVEN}"
  )


def print_phase76_derivation_chain(
  representative,
):
  print_section(
    "Proof-style derivation"
  )

  print(
    "[1] Phase 75 input"
  )
  print()

  print(
    "π_15^8"
  )
  print(
    "= Z{σ₈} ⊕ Z/8{Eσ'}"
  )
  print()

  print(
    "π_16^9"
  )
  print(
    "= Z/16{σ₉}"
  )
  print()

  print(
    "σ₉ = Eσ₈"
  )
  print(
    "2Eσ₈ = E²σ'"
  )
  print()

  print(
    "[2] Suspension kernel"
  )
  print()

  print(
    "E(σ₈)=σ₉"
  )
  print(
    "E(Eσ')=E²σ'=2σ₉"
  )
  print()

  print(
    "Therefore"
  )
  print()

  print(
    "Ker("
    "E: π_15^8 -> π_16^9"
    ")"
  )
  print(
    "= Z{2σ₈-Eσ'}."
  )
  print()

  print(
    "[3] Toda Proposition 4.2 exactness"
  )
  print()

  print(
    "π_17^17 --Δ--> "
    "π_15^8 --E--> π_16^9"
  )
  print()

  print(
    "is exact."
  )
  print()

  print(
    "Hence"
  )
  print()

  print(
    "Im Δ = Ker E"
  )
  print(
    "= Z{2σ₈-Eσ'}."
  )
  print()

  print(
    "[4] Diagonal source generator"
  )
  print()

  print(
    "π_17^17 = Z{ι₁₇}."
  )
  print()

  print(
    "Since the image of Δ is freely "
    "generated by 2σ₈-Eσ',"
  )
  print(
    "the image of the source generator "
    "must equal that generator up to sign."
  )
  print()

  print(
    "[5] Toda Equation (5.16)"
  )
  print()

  print(
    "Δ(ι₁₇)"
  )
  print(
    "= ±(2σ₈-Eσ')."
  )


def print_phase76_provenance(
  representative,
):
  print_section(
    "Provenance / integration"
  )

  final_step = (
    representative[
      "final_step"
    ]
  )

  kernel_step = (
    representative[
      "kernel_step"
    ]
  )

  exactness_step = (
    representative[
      "exactness_step"
    ]
  )

  delta_image_step = (
    representative[
      "delta_image_step"
    ]
  )

  window_step = (
    representative[
      "window_step"
    ]
  )

  pi17_17_step = (
    representative[
      "pi17_17_step"
    ]
  )

  print(
    "Phase 76-2 kernel derived = "
    f"{kernel_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "structural EHP window remains GIVEN = "
    f"{window_step.rule == ProofRule.GIVEN}"
  )

  print(
    "concrete exactness derived = "
    f"{exactness_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "Phase 76-3 Delta image derived = "
    f"{delta_image_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "π_17^17 fact remains GIVEN = "
    f"{pi17_17_step.rule == ProofRule.GIVEN}"
  )

  print(
    "final Equation (5.16) derived = "
    f"{final_step.rule == ProofRule.INFERENCE}"
  )

  print(
    "final Equation (5.16) is GIVEN = "
    f"{final_step.rule == ProofRule.GIVEN}"
  )

  print()

  print(
    "Phase 75 σ₈ reachable = "
    f"{id(representative['sigma8_step']) in representative['ancestor_ids']}"
  )

  print(
    "Phase 75 σ₉ definition reachable = "
    f"{id(representative['sigma9_definition_step']) in representative['ancestor_ids']}"
  )

  print(
    "Phase 75 π_15^8 reachable = "
    f"{id(representative['pi15_8_step']) in representative['ancestor_ids']}"
  )

  print(
    "Phase 75 π_16^9 reachable = "
    f"{id(representative['pi16_9_step']) in representative['ancestor_ids']}"
  )

  print(
    "Phase 75 final aggregate required = "
    f"{id(representative['phase75_aggregate_step']) in representative['ancestor_ids']}"
  )


def print_phase76_non_circularity(
  representative,
):
  print_section(
    "Applicability / non-circularity"
  )

  final_step = (
    representative[
      "final_step"
    ]
  )

  print(
    "final is self-ancestor = "
    f"{id(final_step) in representative['ancestor_ids']}"
  )

  print(
    "final conclusion appears in ancestors = "
    f"{final_step.conclusion in representative['ancestor_conclusions']}"
  )

  pi17_17_step = (
    representative[
      "pi17_17_step"
    ]
  )

  kernel_ancestors = (
    collect_ancestor_steps(
      representative[
        "kernel_step"
      ]
    )
  )

  exactness_ancestors = (
    collect_ancestor_steps(
      representative[
        "exactness_step"
      ]
    )
  )

  delta_image_ancestors = (
    collect_ancestor_steps(
      representative[
        "delta_image_step"
      ]
    )
  )

  print(
    "π_17^17 is used to derive kernel = "
    f"{id(pi17_17_step) in {id(step) for step in kernel_ancestors}}"
  )

  print(
    "π_17^17 is used to derive exactness = "
    f"{id(pi17_17_step) in {id(step) for step in exactness_ancestors}}"
  )

  print(
    "kernel precedes Delta image = "
    f"{id(representative['kernel_step']) in {id(step) for step in delta_image_ancestors}}"
  )

  print(
    "exactness precedes Delta image = "
    f"{id(representative['exactness_step']) in {id(step) for step in delta_image_ancestors}}"
  )


def print_phase76_source():
  print_section(
    "Literature / source"
  )

  print(
    "[Toda Equation (5.16)]"
  )
  print(
    "Locator: Equation (5.16)"
  )
  print(
    "Author: H. Toda"
  )
  print(
    "Source: Composition Methods in "
    "Homotopy Groups of Spheres"
  )
  print(
    "Year: 1962"
  )
  print()
  print(
    "Source statement:"
  )
  print(
    "Ker E is generated by "
    "2σ₈-Eσ'."
  )
  print(
    "Therefore"
  )
  print(
    "Δ(ι₁₇)=±(2σ₈-Eσ')."
  )


def print_phase76_boundary():
  print_section(
    "Phase 76 representative probe boundary"
  )

  print(
    "Displayed:"
  )
  print(
    "  Phase 75 σ₈ / σ₉ input"
  )
  print(
    "  Ker(E)=Z{2σ₈-Eσ'}"
  )
  print(
    "  Delta-E exactness"
  )
  print(
    "  Im(Delta)=Z{2σ₈-Eσ'}"
  )
  print(
    "  π_17^17=Z{ι₁₇}"
  )
  print(
    "  Δ(ι₁₇)=±(2σ₈-Eσ')"
  )
  print(
    "  provenance / non-circularity"
  )
  print()

  print(
    "Not added in Phase 76-6:"
  )
  print(
    "  new mathematical inference rules"
  )
  print(
    "  new theorem semantics"
  )
  print(
    "  generic mixed free/torsion kernel solver"
  )
  print(
    "  generic homomorphism matrix framework"
  )
  print(
    "  generic sign algebra"
  )
  print(
    "  stable homotopy-group model"
  )
  print(
    "  automatic proof narrative generation"
  )
  print(
    "  persistent Proof Repository"
  )
  print()

  print(
    "The proof-style derivation above is "
    "hand-authored presentation code."
  )

  print(
    "It is not yet generated "
    "automatically from the ProofStep graph."
  )

  print()

  print(
    "Next mathematical boundary:"
  )
  print(
    "  Toda Lemma 5.16"
  )


def main():
  print(
    "EHP Proof Tracer"
  )

  print(
    "Phase 76 capability demonstration"
  )

  representative = (
    build_phase76_representative_result()
  )

  print_phase76_result(
    representative
  )

  print_phase76_derivation_chain(
    representative
  )

  print_phase76_provenance(
    representative
  )

  print_phase76_non_circularity(
    representative
  )

  print_phase76_source()

  print_phase76_boundary()


if __name__ == "__main__":
  main()
