from collections import defaultdict

from rule_catalog import (
  RuleRelevanceCategory,
)
import standard_production_applicability_catalog as production_catalog


DEFERRED_BOUNDARY_EXPECTED = {
  RuleRelevanceCategory.BRIDGE: (
    "Toda pi_3^2 define eta_2 as unique Hopf preimage",
    "Toda pi_3^2 eta_2 Hopf relation",
    (
      "Toda 5.4 indeterminacy double nu-prime "
      "generator bridge"
    ),
    (
      "Toda Delta iota_5 twice eta_2 "
      "up-to-sign bridge"
    ),
  ),
  RuleRelevanceCategory.THEOREM_SPECIFIC: (
    "Toda 5.4 nu-prime suspended bracket inclusion",
    (
      "Toda 5.4 t>=1 indeterminacy generated by "
      "eta triple composition"
    ),
    "Toda 5.4 t>=1 up-to-sign integration",
    "Toda 4.5 pi_4^3 finite-cyclic transport",
    "Toda 5.2 pi_4^2 finite-cyclic transport",
    "Toda 5.5 nu-family double suspension transport",
  ),
}


def _build_phase6d12_catalog():
  builder = getattr(
    production_catalog,
    "_phase103_6d15_original_builder",
  )

  value = builder()

  if hasattr(
    value,
    "entries",
  ):
    return value

  raise AssertionError(
    "Phase 103-6D12 catalog builder did not return a catalog"
  )


def _families(
  catalog,
):
  families = defaultdict(
    list
  )

  for entry in catalog.entries():
    families[
      entry.rule.name
    ].append(
      entry
    )

  return {
    name: tuple(
      entries
    )
    for name, entries
    in families.items()
  }


def test_phase103_6d12_assigns_all_10_deferred_boundary_categories():
  catalog = (
    _build_phase6d12_catalog()
  )

  families = _families(
    catalog
  )

  checked = 0

  for (
    expected_category,
    names,
  ) in DEFERRED_BOUNDARY_EXPECTED.items():
    for name in names:
      entries = families[
        name
      ]

      assert all(
        entry.relevance_category
        is expected_category
        for entry in entries
      )

      checked += 1

  assert checked == 10


def test_phase103_6d12_deferred_boundary_affects_exactly_88_catalog_entries():
  catalog = (
    _build_phase6d12_catalog()
  )

  families = _families(
    catalog
  )

  target_names = {
    name
    for names
    in DEFERRED_BOUNDARY_EXPECTED.values()
    for name in names
  }

  affected_entries = tuple(
    entry
    for name in target_names
    for entry in families[
      name
    ]
  )

  assert len(
    affected_entries
  ) == 88

  assert all(
    entry.relevance_category
    is not RuleRelevanceCategory.UNCLASSIFIED
    for entry in affected_entries
  )


def test_phase103_6d12_production_coverage_is_48_classified_219_unclassified():
  catalog = (
    _build_phase6d12_catalog()
  )

  families = _families(
    catalog
  )

  classified = 0
  unclassified = 0

  for entries in families.values():
    categories = {
      entry.relevance_category
      for entry in entries
    }

    assert len(
      categories
    ) == 1

    category = next(
      iter(
        categories
      )
    )

    if (
      category
      is RuleRelevanceCategory.UNCLASSIFIED
    ):
      unclassified += 1
    else:
      classified += 1

  assert len(
    families
  ) == 267

  assert classified == 48
  assert unclassified == 219


def test_phase103_6d12_adds_no_structural_or_map_property_family():
  catalog = (
    _build_phase6d12_catalog()
  )

  families = _families(
    catalog
  )

  target_names = {
    name
    for names
    in DEFERRED_BOUNDARY_EXPECTED.values()
    for name in names
  }

  assert all(
    entry.relevance_category
    in {
      RuleRelevanceCategory.BRIDGE,
      RuleRelevanceCategory.THEOREM_SPECIFIC,
    }
    for name in target_names
    for entry in families[
      name
    ]
  )


def test_phase103_6d12_catalog_size_and_fixed_point_safety_are_unchanged():
  catalog = (
    _build_phase6d12_catalog()
  )

  entries = (
    catalog.entries()
  )

  assert len(
    entries
  ) == 1188

  assert all(
    entry.fixed_point_safe
    is False
    for entry in entries
  )
