from pathlib import Path

REFERENCES = Path("toda_group_proof_narrative_references.py")
INTEGRATION_TEST = Path(
  "tests/test_phase157_r4_r3_reference_selection_integration.py"
)
RETENTION_TEST = Path(
  "tests/test_phase157_r4_r3_repair1_reference_retention.py"
)

OLD_HASH_BLOCK = '  retained_reference_keys = {\n    (\n      entry.reference,\n      entry.proof_steps,\n    )\n    for entry in filtered_entries\n  }\n'
NEW_HASH_BLOCK = '  retained_reference_keys = {\n    (\n      entry.reference.locator,\n      entry.reference.label,\n      tuple(\n        id(\n          proof_step\n        )\n        for proof_step in entry.proof_steps\n      ),\n    )\n    for entry in filtered_entries\n  }\n'
OLD_MEMBERSHIP_BLOCK = '      (\n        entry.reference,\n        entry.proof_steps,\n      )\n      in retained_reference_keys\n'
NEW_MEMBERSHIP_BLOCK = '      (\n        entry.reference.locator,\n        entry.reference.label,\n        tuple(\n          id(\n            proof_step\n          )\n          for proof_step in entry.proof_steps\n        ),\n      )\n      in retained_reference_keys\n'

INTEGRATION_TEST_TEXT = 'from dataclasses import dataclass\n\nfrom proof import (\n  InferenceRule,\n  LiteratureReference,\n  ProofRule,\n  ProofStep,\n)\nfrom toda_group_proof_narrative_references import (\n  TodaGroupProofNarrativeReferenceEntry,\n  filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary,\n)\n\n\n@dataclass(frozen=True)\nclass _TargetGroup:\n  group_dimension: int\n  sphere_dimension: int\n\n\n@dataclass(frozen=True)\nclass _RelationLike:\n  lhs: _TargetGroup\n  rhs: str\n\n\ndef _reference(\n  locator: str,\n) -> LiteratureReference:\n  return LiteratureReference(\n    label="Toda " + locator,\n    locator=locator,\n  )\n\n\ndef _step(\n  rule_name: str,\n  locator: str,\n  conclusion,\n) -> ProofStep:\n  return ProofStep(\n    conclusion=conclusion,\n    premises=(),\n    rule=ProofRule.INFERENCE,\n    inference_rule=InferenceRule(\n      name=rule_name,\n      literature_reference=_reference(\n        locator\n      ),\n    ),\n  )\n\n\ndef test_phase157_r4_r3_filter_keeps_only_earlier_fixed_same_theorem_group_result():\n  root_step = _step(\n    "Toda Proposition 5.15 pi_15^8 final decomposition",\n    "Proposition 5.15",\n    _RelationLike(\n      lhs=_TargetGroup(\n        group_dimension=15,\n        sphere_dimension=8,\n      ),\n      rhs="target",\n    ),\n  )\n  earlier_step = _step(\n    "Toda Proposition 5.15 pi_14^7 finite cyclic",\n    "Proposition 5.15",\n    "earlier fixed group result",\n  )\n  target_step = _step(\n    "Toda Proposition 5.15 pi_15^8 final decomposition",\n    "Proposition 5.15",\n    "target fixed group result",\n  )\n  internal_step = _step(\n    "Toda Proposition 5.15 sigma_8 transported decomposition",\n    "Proposition 5.15",\n    "proof-internal decomposition",\n  )\n\n  entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=_reference(\n      "Proposition 5.15"\n    ),\n    proof_steps=(\n      earlier_step,\n      target_step,\n      internal_step,\n    ),\n  )\n\n  filtered = (\n    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(\n      (\n        entry,\n      ),\n      root_step,\n    )\n  )\n\n  assert len(\n    filtered\n  ) == 1\n  assert filtered[\n    0\n  ].proof_steps == (\n    earlier_step,\n  )\n\n\ndef test_phase157_r4_r3_filter_removes_proof_internal_prop511_step():\n  root_step = _step(\n    "Toda Proposition 5.15 pi_12^5 finite cyclic",\n    "Proposition 5.15",\n    _RelationLike(\n      lhs=_TargetGroup(\n        group_dimension=12,\n        sphere_dimension=5,\n      ),\n      rhs="target",\n    ),\n  )\n  fixed_step = _step(\n    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",\n    "Proposition 5.11",\n    "fixed group result",\n  )\n  internal_step = _step(\n    "Toda Proposition 5.11 pi_12^6 suspension isomorphism",\n    "Proposition 5.11",\n    "proof-internal map property",\n  )\n\n  entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=_reference(\n      "Proposition 5.11"\n    ),\n    proof_steps=(\n      fixed_step,\n      internal_step,\n    ),\n  )\n\n  filtered = (\n    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(\n      (\n        entry,\n      ),\n      root_step,\n    )\n  )\n\n  assert len(\n    filtered\n  ) == 1\n  assert filtered[\n    0\n  ].proof_steps == (\n    fixed_step,\n  )\n\n\ndef test_phase157_r4_r3_filter_is_noop_outside_representative_targets():\n  root_step = _step(\n    "Toda Proposition 5.15 pi_13^6 finite cyclic",\n    "Proposition 5.15",\n    _RelationLike(\n      lhs=_TargetGroup(\n        group_dimension=13,\n        sphere_dimension=6,\n      ),\n      rhs="target",\n    ),\n  )\n  step = _step(\n    "Toda Proposition 5.15 pi_12^5 finite cyclic",\n    "Proposition 5.15",\n    "fixed group result",\n  )\n  entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=_reference(\n      "Proposition 5.15"\n    ),\n    proof_steps=(\n      step,\n    ),\n  )\n\n  filtered = (\n    filter_phase157_r4_representative_reference_entries_by_fixed_statement_boundary(\n      (\n        entry,\n      ),\n      root_step,\n    )\n  )\n\n  assert filtered == (\n    entry,\n  )\n'
RETENTION_TEST_TEXT = 'from dataclasses import dataclass\n\nfrom proof import (\n  InferenceRule,\n  LiteratureReference,\n  ProofRule,\n  ProofStep,\n)\nfrom toda_group_proof_narrative_references import (\n  TodaGroupProofNarrativeReferenceEntry,\n  restore_phase157_r4_representative_fixed_reference_entries_after_body_usage,\n)\n\n\n@dataclass(frozen=True)\nclass _TargetGroup:\n  group_dimension: int\n  sphere_dimension: int\n\n\n@dataclass(frozen=True)\nclass _RelationLike:\n  lhs: _TargetGroup\n  rhs: str\n\n\ndef _reference(\n  locator: str,\n) -> LiteratureReference:\n  return LiteratureReference(\n    label="Toda " + locator,\n    locator=locator,\n  )\n\n\ndef _step(\n  rule_name: str,\n  locator: str,\n  conclusion,\n  premises=(),\n) -> ProofStep:\n  return ProofStep(\n    conclusion=conclusion,\n    premises=premises,\n    rule=ProofRule.INFERENCE,\n    inference_rule=InferenceRule(\n      name=rule_name,\n      literature_reference=_reference(\n        locator\n      ),\n    ),\n  )\n\n\ndef test_phase157_r4_r3_restore_uses_step_identity_without_hashing_recursive_proof_graph():\n  deep_leaf = _step(\n    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",\n    "Proposition 5.11",\n    "leaf",\n  )\n  deep_middle = _step(\n    "Toda Proposition 5.11 pi_11^5 nu_5 squared",\n    "Proposition 5.11",\n    "middle",\n    premises=(\n      deep_leaf,\n    ),\n  )\n  fixed_step = _step(\n    "Toda Lemma 5.13 sigma triple-prime definition",\n    "Lemma 5.13",\n    "sigma triple-prime fixed statement",\n    premises=(\n      deep_middle,\n    ),\n  )\n  retained_step = _step(\n    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",\n    "Proposition 5.11",\n    "retained fixed result",\n  )\n  root_step = _step(\n    "Toda Proposition 5.15 pi_12^5 finite cyclic",\n    "Proposition 5.15",\n    _RelationLike(\n      lhs=_TargetGroup(\n        group_dimension=12,\n        sphere_dimension=5,\n      ),\n      rhs="target",\n    ),\n    premises=(\n      fixed_step,\n      retained_step,\n    ),\n  )\n\n  lemma_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=_reference(\n      "Lemma 5.13"\n    ),\n    proof_steps=(\n      fixed_step,\n    ),\n  )\n  prop511_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=2,\n    reference=_reference(\n      "Proposition 5.11"\n    ),\n    proof_steps=(\n      retained_step,\n    ),\n  )\n  filtered_prop511_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=prop511_entry.reference,\n    proof_steps=prop511_entry.proof_steps,\n  )\n\n  (\n    restored_entries,\n    restored_lines,\n    restored_body,\n  ) = (\n    restore_phase157_r4_representative_fixed_reference_entries_after_body_usage(\n      (\n        lemma_entry,\n        prop511_entry,\n      ),\n      {\n        1: (\n          "sigma-triple-prime fixed",\n        ),\n        2: (\n          "pi10_4 fixed",\n        ),\n      },\n      (\n        filtered_prop511_entry,\n      ),\n      {\n        1: (\n          "pi10_4 fixed",\n        ),\n      },\n      "uses [R1]",\n      root_step,\n      frozenset(\n        {\n          id(\n            fixed_step\n          ),\n          id(\n            retained_step\n          ),\n        }\n      ),\n    )\n  )\n\n  assert tuple(\n    entry.reference.locator\n    for entry in restored_entries\n  ) == (\n    "Lemma 5.13",\n    "Proposition 5.11",\n  )\n  assert restored_lines == {\n    1: (\n      "sigma-triple-prime fixed",\n    ),\n    2: (\n      "pi10_4 fixed",\n    ),\n  }\n  assert restored_body == "uses [R2]"\n\n\ndef test_phase157_r4_r3_restore_does_not_add_unused_fixed_reference():\n  unused_step = _step(\n    "Toda Lemma 5.13 sigma triple-prime definition",\n    "Lemma 5.13",\n    "unused fixed statement",\n  )\n  retained_step = _step(\n    "Toda Proposition 5.11 pi_10^4 generated by nu_4 squared",\n    "Proposition 5.11",\n    "retained fixed result",\n  )\n  root_step = _step(\n    "Toda Proposition 5.15 pi_12^5 finite cyclic",\n    "Proposition 5.15",\n    _RelationLike(\n      lhs=_TargetGroup(\n        group_dimension=12,\n        sphere_dimension=5,\n      ),\n      rhs="target",\n    ),\n  )\n\n  unused_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=_reference(\n      "Lemma 5.13"\n    ),\n    proof_steps=(\n      unused_step,\n    ),\n  )\n  retained_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=2,\n    reference=_reference(\n      "Proposition 5.11"\n    ),\n    proof_steps=(\n      retained_step,\n    ),\n  )\n  filtered_retained_entry = TodaGroupProofNarrativeReferenceEntry(\n    number=1,\n    reference=retained_entry.reference,\n    proof_steps=retained_entry.proof_steps,\n  )\n\n  (\n    restored_entries,\n    restored_lines,\n    restored_body,\n  ) = (\n    restore_phase157_r4_representative_fixed_reference_entries_after_body_usage(\n      (\n        unused_entry,\n        retained_entry,\n      ),\n      {\n        1: (\n          "unused",\n        ),\n        2: (\n          "retained",\n        ),\n      },\n      (\n        filtered_retained_entry,\n      ),\n      {\n        1: (\n          "retained",\n        ),\n      },\n      "uses [R1]",\n      root_step,\n      frozenset(\n        {\n          id(\n            retained_step\n          ),\n        }\n      ),\n    )\n  )\n\n  assert len(\n    restored_entries\n  ) == 1\n  assert (\n    restored_entries[\n      0\n    ].reference.locator\n    == "Proposition 5.11"\n  )\n  assert restored_lines == {\n    1: (\n      "retained",\n    ),\n  }\n  assert restored_body == "uses [R1]"\n'


def main():
  for path in (
    REFERENCES,
    INTEGRATION_TEST,
    RETENTION_TEST,
  ):
    if not path.exists():
      raise SystemExit(
        f"target not found: {path}"
      )

  references_text = REFERENCES.read_text(
    encoding="utf-8"
  )

  if OLD_HASH_BLOCK not in references_text:
    raise SystemExit(
      "recursive hash block not found"
    )

  if OLD_MEMBERSHIP_BLOCK not in references_text:
    raise SystemExit(
      "recursive hash membership block not found"
    )

  references_text = references_text.replace(
    OLD_HASH_BLOCK,
    NEW_HASH_BLOCK,
    1,
  )
  references_text = references_text.replace(
    OLD_MEMBERSHIP_BLOCK,
    NEW_MEMBERSHIP_BLOCK,
    1,
  )

  REFERENCES.write_text(
    references_text,
    encoding="utf-8",
    newline="\n",
  )

  INTEGRATION_TEST.write_text(
    INTEGRATION_TEST_TEXT,
    encoding="utf-8",
    newline="\n",
  )

  RETENTION_TEST.write_text(
    RETENTION_TEST_TEXT,
    encoding="utf-8",
    newline="\n",
  )

  print(
    "Phase157-R4-R3 repair2 applied."
  )
  print(
    f"updated: {REFERENCES.resolve()}"
  )
  print(
    f"replaced with lightweight tests: {INTEGRATION_TEST.resolve()}"
  )
  print(
    f"replaced with lightweight tests: {RETENTION_TEST.resolve()}"
  )


if __name__ == "__main__":
  main()
